# spot-cluster.yaml

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: roboshop
  region: us-east-1
  availabilityZones:
  - us-east-1a
  - us-east-1b

managedNodeGroups:
- name: spot
  instanceTypes: ["T3.small"]
  spot: true
  desiredCapacity: 2