apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: roboshop
  region: us-east-1

iam:
  withOIDC: true   # ✅ important fix

nodeGroups:
  - name: ng-1
    instanceType: t3.medium   # ❗ change from t3.micro
    desiredCapacity: 2